"""initial schema

Revision ID: e2f2d58b8096
Revises: 
Create Date: 2026-07-06 06:47:20.915887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f2d58b8096'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('faculty', sa.String(), nullable=True))
    op.add_column('students', sa.Column('programme', sa.String(), nullable=True))
    op.add_column('students', sa.Column('level', sa.String(), nullable=True))
    op.add_column('students', sa.Column('year_of_admission', sa.String(), nullable=True))
    op.add_column('students', sa.Column('expected_graduation', sa.String(), nullable=True))
    op.drop_column('students', 'grade_level')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('other_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('university_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', 'other', 'prefer_not_to_say', name='gender'), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'university_name')
    op.drop_column('users', 'other_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('students', sa.Column('grade_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'expected_graduation')
    op.drop_column('students', 'year_of_admission')
    op.drop_column('students', 'level')
    op.drop_column('students', 'programme')
    op.drop_column('students', 'faculty')
    # ### end Alembic commands ###
